USE easyreader;
DROP TABLE IF EXISTS categoria;
CREATE TABLE categoria (
id INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(63) NOT NULL,
descripcion VARCHAR(127),
PRIMARY KEY (id) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
