USE easyreader;
DROP TABLE IF EXISTS canal;
CREATE TABLE canal (
id INT NOT NULL AUTO_INCREMENT,
titulo VARCHAR(127) NOT NULL,
enlace VARCHAR(127) NOT NULL,
url VARCHAR(127) NOT NULL,
descripcion VARCHAR(127),
categoria VARCHAR(63),
PRIMARY KEY (id) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
